# Generated by Django 5.1.3 on 2024-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_livres_membres_emprunts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livres',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
