# Generated by Django 5.1.3 on 2024-12-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='annee_publication',
            field=models.DateField(),
        ),
    ]
