# Generated by Django 5.1.3 on 2024-12-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_book_annee_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
