# Generated by Django 5.1.3 on 2024-12-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunts',
            name='id_livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.book'),
        ),
        migrations.AlterField(
            model_name='emprunts',
            name='id_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.membre'),
        ),
        migrations.RemoveField(
            model_name='membre',
            name='livres',
        ),
        migrations.AddField(
            model_name='emprunts',
            name='date_rendu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunts',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunts',
            name='status',
            field=models.CharField(choices=[('O', 'Rendu'), ('C', 'en_cours'), ('N', 'Non_rendu')], default='C', max_length=50),
        ),
        migrations.AlterField(
            model_name='emprunts',
            name='date_emprunt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
        migrations.DeleteModel(
            name='Membres',
        ),
    ]
