# Generated by Django 5.1.3 on 2024-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_emprunts_id_livre_alter_emprunts_id_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunts',
            name='penalite',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
