# Generated by Django 5.1.3 on 2024-12-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_emprunts_penalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunts',
            name='date_emprunt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
