# Generated by Django 5.1.3 on 2024-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_emprunts_date_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunts',
            name='penalite',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
